### ISSUE TITLE
Stripe payment

### ISSUE THREAD

**Issue by kleppy** [kleppy/corknfork#14]
We need to implement a payment system. The path of least resistance is to just use stripe as a donation mechanism since we'd need to actually have inventory and take into account tax and verify age. 

Integrate the Stripe payment platform. (Even if you don’t create an e-commerce app, set up the app to accept charitable donations)

**Comment by kleppy** [comment]
https://docs.stripe.com/js

**Comment by kleppy** [comment]
https://docs.stripe.com/stripe-js/elements/payment-request-button

**Comment by chelleyoungw** [comment]
**not required** could add as donation?
