### ISSUE TITLE
Pseudocode project

### ISSUE THREAD

**Issue by kleppy** [kleppy/corknfork#2]
Write the pseudo code for the flow of the application .  How users interact, login, search, filter, delete, pair.

**Comment by kleppy** [comment]
**UAC FOR PAIRING SITE**

AS A USER 
WHEN I GO TO THE SITE 
THEN I SEE LATEST (Wine, pairings, foods) listed in the main content window by category
I ALSO SEE on the top side navigation bar , Login, search , home
WHEN I CLICK LOGIN 
THEN I am taken to my wine cellar (previous searches and pairings)
FROM LOGIN I Can make additional searches from the front page and add to my cellar. 
When I CLICK HOME, I am taken to my cellar , or asked to LOGIN. 
FROM THE SEARCH BAR  I can perform multi select searches based on all attributes of each object. 
FROM THE API I can add new items, updates existing items, and delete existing items.

**Comment by JesseDenier** [comment]
Once this is complete it should be easy to translate it into the usage paragraph of the README
